name: ARM64 Cross-Compilation

on:
  workflow_dispatch:  # 手动触发

jobs:
  cross-compile-arm64:
    name: Cross-compile for ARM64
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up cross-compilation environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            build-essential \
            autoconf automake libtool \
            libcap-ng-dev \
            python3-dev swig \
            libkrb5-dev \
            libldap-dev \
            file

      - name: Configure for ARM64
        run: |
          autoreconf -f --install
          # 设置交叉编译环境
          export CC=aarch64-linux-gnu-gcc
          export CXX=aarch64-linux-gnu-g++
          export AR=aarch64-linux-gnu-ar
          export RANLIB=aarch64-linux-gnu-ranlib
          
          ./configure \
            --host=aarch64-linux-gnu \
            --build=x86_64-linux-gnu \
            --with-python3=yes \
            --enable-gssapi-krb5=yes \
            --with-aarch64 \
            --with-libcap-ng=yes \
            --without-golang \
            --enable-zos-remote \
            --enable-experimental \
            --with-io_uring

      - name: Build ARM64 binaries
        run: |
          make -j$(nproc)
          # 验证二进制文件架构
          find . -type f -executable -exec sh -c "file {} | grep -q 'ARM aarch64'" \; -ls

      - name: Package ARM64 binaries
        run: |
          # 创建包含所有构建产物的目录
          mkdir -p artifacts/arm64-bin
          
          # 复制所有可执行文件和库
          find . -type f -executable -exec cp --parents {} artifacts/arm64-bin/ \;
          find . -name '*.so' -exec cp --parents {} artifacts/arm64-bin/ \;
          
          # 创建压缩包
          tar -czvf arm64-binaries.tar.gz -C artifacts/arm64-bin .
          
      - name: Upload ARM64 binaries
        uses: actions/upload-artifact@v4
        with:
          name: arm64-binaries
          path: arm64-binaries.tar.gz
          retention-days: 7
